### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by AndBendWeWereHere** [meub/aura-frame-downloader#6]
Hi, first thanks for developing this!  But just tried running, and it keeps erroring out on Item 1, so I don't *think* it's related to throttling.  Wondering if it's still working for others, or if perhaps Aura has modified their API? @meub 
![screenshot](https://github.com/meub/aura-frame-downloader/assets/144620614/1b73ddfb-3477-4e61-aefe-bacb0d3ea2ad)

**Comment by vukelich** [comment]
If you're running this on Windows, then I'd imagine the problem is because the file name contains `:` characters. The script will try to create a file called `images\2023-09-10T04:55:39.525Z_81260ec4-4f96-11ee-9a4c-0a9b723fb325.jpeg` and maybe throw an error saying the drive by the name `images\2023-09-10T04` doesn't exist. 

Fix should be easy. 

1. Open the `download-aura-photos.py` file in your favorite text editor (Notepad, WordPad, VS Code, etc.).
2. Find this set of lines:
```python
            # make a unique new_filename using
            #  item['taken_at'] + item['id'] + item['file_name']'s extension
            new_filename = item['taken_at'] + "_" + item['id'] + os.path.splitext(item['file_name'])[1]
```
3. Replace those with these lines. Indentation does matter! If you copy and past the below lines, then you should be safe.
```python
            # make a unique new_filename using
            #  item['taken_at'] + item['id'] + item['file_name']'s extension
            # But clean the timestamp to be Windows-friendly
            clean_time = item['taken_at'].replace(':', '-')
            new_filename = clean_time + "_" + item['id'] + os.path.splitext(item['file_name'])[1]
```

Heads up: I have no Python experience, and I just stumbled onto this wondering how other folks have written scripts to interact with Aura frames for my own pet project. I won't be following up, but just tossing this comment out anyway.

For the maintainers or other programmers: I created a little Python test to see if this is how string manipulation works in Python. [This link expires 2024-05-27 for some online Python playground.](https://www.online-python.com/emPb3ZM2aK) If you have better advice for string operations, please feel free to correct me. This repo doesn't do much for error handling, so neither did I in my fast advice.

```python
# code if link is expired
import os

item = {
    'taken_at' : '2023-09-10T04:55:39.525Z',
    'id': '81260ec4-4f96-11ee-9a4c-0a9b723fb325',
    'file_name': 'somefile.jpeg'
}

clean_time = item['taken_at'].replace(':', '-')
new_filename = clean_time + "_" + item['id'] + os.path.splitext(item['file_name'])[1]

print (new_filename)
```

**Comment by meub** [comment]
Thanks for this! I've fixed this issue with your suggestion.
